config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'friendships#my_friends'
  get 'search_friends', to: 'friendships#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true
    # from IEX lookup gem
    def self.new_lookup(ticker_symbol)
        client = IEX::Api::Client.new(
            publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
            secret_token: Rails.application.credentials.iex_client[:secret_api_key],
            endpoint: 'https://sandbox.iexapis.com/v1'
          )
        # create a new Stock object, with the ticker symbol, company name, and price.
        # check the IEX gem documentation for information on how each of these methods are called
        begin  
          new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
        rescue => exception
          return nil
        end
    end
    def self.check_db(ticker_symbol)
      where(ticker: ticker_symbol).first
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    def search
        # if stock found, render price,
        # if stock not found, alert user
        if params[:stock].present?
        # in stock.rb file
        # @stock variable for view
            @stock = Stock.new_lookup(params[:stock])
            if @stock
                respond_to do |format|
                    format.js { render partial: 'users/result' }
                end
            else
                respond_to do |format|
                    flash.now[:alert] = "Please enter a valid symbol to search"
                    format.js { render partial: 'users/result' }
                end
            end
        else
            respond_to do |format|
                flash.now[:alert] = "Please enter a symbol to search"
                format.js { render partial: 'users/result' }
            end
        end
    end
end

app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @tracked_stocks.each do |stock| %>
          <tr>
            <th scope="row"><%= stock.ticker %></th>
            <td><%= stock.name %></td>
            <td><%= stock.last_price %></td>
            <td><% if current_user.can_track_stock?(stock.ticker) %>
                <%= link_to 'Add to Portfolio', user_stocks_path(user: current_user, ticker: stock.ticker), class: "btn btn-success", method: :post  %>
              <% elsif current_user.id != @user.id %>
                <span class="badge badge-secondary">
                  You are already tracking
                  <% if !current_user.under_stock_limit? %>
                    10 stocks
                  <% end %>
                  <% if current_user.stock_already_tracked?(stock.ticker) %>
                    This stock
                  <% end %>
                </span>
              <% end %>
              <% if current_user.id == @user.id  %><%= link_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-sm btn-warning'%><% end %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>