config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'friendships#my_friends'
  get 'search_friends', to: 'friendships#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

# if the stock is already tracked
# create a stock variable, where we check the database for an existing ticker symbol
# if one does not exist, we return false
# if one does exist, we return true / false where the stock exists as a tracked stock in the user table
def stock_already_tracked?(ticker_symbol)
  stock = Stock.check_db(ticker_symbol)
  return false unless stock
  stocks.where(id: stock.id).exists?
end

# we check if the current number of stocks associated with the user is less than 10
def under_stock_limit?
  stocks.count < 10
end

# if they are under the stock limit, and the stock is not being tracked,
# let them track the stock
def can_track_stock?(ticker_symbol)
  under_stock_limit? && !stock_already_tracked?(ticker_symbol)
end

def full_name
  return "#{first_name} #{last_name}" if first_name || last_name
  "Anonymous"
end

### Search methods for finding users  ###

# Strip all whitespace
# return results from other methods, or nil if nothing returned back
# returns unique values of results from all 3 methods

def self.search(param)
  param.strip!
  to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
  return nil unless to_send_back
  to_send_back
end

# Search for first_name, last_name, and email fields
# given params
def self.first_name_matches(param)
  matches('first_name',param)
end
def self.last_name_matches(param)
  matches('last_name',param)
end
def self.email_matches(param)
  matches('email',param)
end

# method to do searches on users, when trying to find users
# search for mathes on a specific field name, given a specific param
def self.matches(field_name, param)
  where("#{field_name} like ?", "%#{param}%")
end

def except_current_user(users)
  users.reject { |user| user.id == self.id }
end
def not_friends_with?(id_of_friend)
  !self.friends.where(id: id_of_friend).exists?
  
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
    @user = current_user
  end
  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>
<%# Only load the page data if the @stock variable exists %>
<%# On first load, this will not exist, because a stock query has not yet been requested %>
<% if @stock %>
  <div class="card card-header results-block">
  <%# comes from the controller %>
    <strong>Symbol: </strong><%= @stock.ticker %>
    <strong>Name: </strong><%= @stock.name %>
    <strong>Price: </strong><%= @stock.last_price %>

    <%# these methods come from the user model %>
    <%# if the user is able to track stock, show the "add to portfolio" button %>
    <%# if not, then you either are tracking too many stocks (> 10), or you are already tracking a stock that you are trying to track again %>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to 'Add to Portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker), class: "btn btn-success", method: :post  %>
    <% else %>
      <span class="badge badge-secondary">
        You are already tracking
        <% if !current_user.under_stock_limit? %>
          10 stocks
        <% end %>
        <% if current_user.stock_already_tracked?(@stock.ticker) %>
          This stock
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/result.html' %>' 

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<div class="search-area">
  <h3>Search Stocks</h3>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do  %>
          <%# from FontAwesome gem %>
          <%= fa_icon 'search 2x'  %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">
</div>
<%# @tracked_stocks is from the Users Controller %>
<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>
<div class="card card-header results-block">
  <table class="col-md-12">
    <tbody>
      <tr>
        <%# comes from the controller %>
        <td><strong>Name: </strong><%= @user.full_name %></td>
        <td><strong>Email: </strong><%= @user.email %></td>
          <%# these methods come from the user model %>
          <%# if the user is able to track stock, show the "add to portfolio" button %>
          <%# if not, then you either are tracking too many stocks (> 10), or you are already tracking a stock that you are trying to track again %>
          <% if current_user.not_friends_with?(@user.id) %>
            <td> <%= link_to 'Follow Friend', friendships_path(friend: @user), class: "btn btn-success", method: :post  %> </td>
        <% else %>
          <span class="badge badge-secondary">You are already friends</span>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>
<%# @tracked_stocks is from the Users Controller %>
<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% else %>
<p class='lead'>This user is not tracking any stocks</p>
<% end %>