config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'friendships#my_friends'
  get 'search_friends', to: 'friendships#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    def my_friends
      @followed_friends = current_user.friends
    end
    def create
        friend = User.find(params[:friend])
        current_user.friendships.build(friend_id)
        if current_user.save
            flash[:notice] = "Following friend"
        else
            flash[:alert] = "There was something wrong with the tracking request"
        end
        redirect_to my_firends_path
    end
    def destroy
        friendship = current_user.friendships.where(friend_id: params[:id]).first
        friendship.destroy
        flash[:notice] = "Stopped following"
        redirect_to my_friends_path
    end
    def search
        # if stock found, render price,
        # if stock not found, alert user
        if params[:friend].present?
        # in stock.rb file
        # @friend variable for view
        # the search method can be found in the User controller
            @friends = User.search(params[:friend])
            @friends = current_user.except_current_user(@friends)
            if @friends
                respond_to do |format|
                    format.js { render partial: 'friendships/result' }
                end
            else
                respond_to do |format|
                    flash.now[:alert] = "Couldn't find user"
                    format.js { render partial: 'friendships/result' }
                end
            end
        else
            respond_to do |format|
                flash.now[:alert] = "Please enter a friend name or email to search a symbol to search"
                format.js { render partial: 'friendships/result' }
            end
        end
    end
  end
  

app/views/friendships/_list.html.erb
<div class="row">
    <div class="col-9">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Email</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @followed_friends.each do |friend| %>
            <tr>
              <th scope="row"><%= friend.email %></th>
              <td><%= friend.first_name %></td>
              <td><%= friend.last_name %></td>
              <td><%= link_to 'View Profile', user_path(friend), class: 'btn btn-sm btn-success'%>
              <%= link_to 'Stop following', friendship_path(friend), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-sm btn-warning'%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/friendships/_result.hmtl.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>
<%# Only load the page data if the @stock variable exists %>
<%# On first load, this will not exist, because a stock query has not yet been requested %>
<% if @friends %>
  <div class="card card-header results-block">
  <table class="col-md-12">
  <tbody>

    <% @friends.each do |friend| %>
    <tr>
      <%# comes from the controller %>
      <td><strong>Name: </strong><%= friend.full_name %></td>
      <td><strong>Email: </strong><%= friend.email %></td>
      <td><strong>Actions: </strong><%= link_to "View Profile", user_path(friend), class: "btn btn-sm btn-success"%>
      <%# these methods come from the user model %>
      <%# if the user is able to track stock, show the "add to portfolio" button %>
      <%# if not, then you either are tracking too many stocks (> 10), or you are already tracking a stock that you are trying to track again %>
      <% if current_user.not_friends_with?(friend.id %>
      <%= link_to 'Follow Friend', friendships_path(friend: friend), class: "btn btn-success", method: :post  %></td>
      <% else %>
      <span class="badge badge-secondary">You are already friends</span>
      <% end %>
    </tr>
    <% end %>
    </tbody>
    </table>
  </div>
<% end %>

app/views/friendships/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'friendships/result.html' %>' 

app/views/friendships/my_friends.html.erb
<h1>My Friends</h1>
<h3>Friends</h3>
<div class="search-area">
  <h3>Search Stocks</h3>
  <%= form_tag search_friends_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Friend Email", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do  %>
          <%# from FontAwesome gem %>
          <%= fa_icon 'search 2x'  %>
        <% end %>
      </div>
    </div>
  <% end %>


<% if !@followed_friends.empty? %>
  <%= render 'friendships/list' %>
<% end %>